// code generated by [generate-resource-dart-code] vscode-extension.
class AssetsImages {
  static const android12splashPng = 'assets/images/android12splash.png';
  static const splashPng = 'assets/images/splash.png';
}

class AssetsSvgs {

}

